const placeholders = {
  movies: [
    "The Room",
    "Samurai Cop",
    "Demolition Man",
    "The Wicker Man",
    "Blade 3",
    "Austin Powers",
    "Scary Movie",
    "Scary Movie 2",
    "Scary Movie 3",
    "Scary Movie 4",
    "Scary Movie 5",
    "Clown",
    "The Fast and the Furious",
    "2 Fast 2 Furious",
    "Fast 6",
    "Drug War",
    "Fast 7",
    "Alien: Resurrection",
    "Terminator: Genisys",
    "Three",
    "The Dinner",
    "Expendables 3",
    "Mimic 2",
    "Deep Star Six",
    "Batman vs Superman",
    "The Tag-Along",
    "The Secret of Moonacre",
    "The Trust",
    "Beyond the Gates",
    "Gantz: 0",
    "A Wrinkle in Time",
    "Catwoman",
    "Atlantic Rim",
    "Sharknado",
    "Mega Shark vs Giant Octopus",
    "Fant4stic Four",
    "Rage",
    "Bangkok Dangerous",
    "Drive Angry",
    "Sun Choke",
    "Taipei Story"
  ]
};

export default placeholders;
